on:
  workflow_dispatch:

  pull_request:
    branches:
      - 'develop'
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The PR was merged

      - uses: actions/checkout@v3
        with:
          ref: foo
          fetch-depth: 0

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git merge origin/develop --no-ff --no-edit
          git push
